### ISSUE TITLE
Non blocking io implementation

### ISSUE THREAD

**Issue by Spartaques** [laravel/octane#511] opened 2022-04-29 22:55 UTC
Hello guys. I have a big project with laravel and i’a using octane with swoole. And i have expirience with nodejs python golang and writing code asynchronous using all this shit. For me, octane is good but it is not asynchronous. It’s based on async solution, but code working synchronously. But i want to use non blocking io in my programs so my program will be more performant. There are many reasons for non blocking io. So my question is:
Do you guys have any plans implementing non blocking io in laravel like some frameworks do using swoole (hyperf, easy swoole etc)? This means enabling coroutines etc.

Its very important for me to know, because if you not planned to do this, i will implement it myself for my case.

**Comment by sy-records** [comment] 2022-04-29 23:44
Duplicate of #503.

**Comment by driesvints** [comment] 2022-04-30 07:33
Please indeed see previous issues. Thanks @sy-records

**Closed** 2022-04-30 07:33 UTC
