### ISSUE TITLE
Issue streaming file in a video html tag

### ISSUE THREAD

**Issue by L3o-pold** [laravel/octane#763] opened 2023-10-23 18:32 UTC
### Octane Version

2.1.0

### Laravel Version

10.28.0

### PHP Version

8.2.10

### What server type are you using?

Swoole

### Server Version

5.0.3

### Description

When using Swoole or Open swoole, streaming a video file (mp4 hevc) and trying to display it in a video html tag result in an empty video player.

Using the same code without Octane works as expected (video player displayed and able to play the video)

### Steps To Reproduce

```
git clone https://github.com/L3o-pold/bug-report.git
php artisan octane:start
```

Open http://127.0.0.1:8000 on a Chrome browser. 

<img width="976" alt="image" src="https://github.com/laravel/octane/assets/4710495/b8579fa6-16e1-480b-9d59-0cf1d3c4ea43">

Video fails to load with following error: 

```
FFmpegDemuxer: open context failed
Error Group: PipelineStatus
Error Code: 12
Stacktrace: media/filters/ffmpeg_demuxer.cc:1256
```

Without Octane (`php artisan serve`) the video is playable without any issue

<img width="965" alt="image" src="https://github.com/laravel/octane/assets/4710495/5d20671b-2d57-4d6c-aa4a-77f134041b0a">

**Comment by sy-records** [comment] 2023-11-27 14:19
@L3o-pold Modify the header to restore normal, you can try it.

```
Route::get('/video', function () {
    return response()->download(
        resource_path('videos/TSU_640x360.mp4'),
        null,
        ['Accept-Ranges' => null]
    );
});
```

---

This seems to be a swoole bug. Introduced by https://github.com/swoole/swoole-src/commit/8e37910fcb12cec11b4a735d3a12bd39b8938817  cc @Yurunsoft @NathanFreeman

Duplicate of https://github.com/hyperf/hyperf/issues/6223

**Comment by L3o-pold** [comment] 2023-11-27 14:25
@sy-records yes and no, without streaming, you are able to play the video, but you are not able to go forward or backward. Streaming is needed for this functionality.

**Comment by L3o-pold** [comment] 2023-12-19 14:23
It was provided in my first message: https://github.com/L3o-pold/bug-report.git

**Comment by sy-records** [comment] 2023-12-26 05:03
@L3o-pold You can compile the master code for swoole-src to test it and see if it solves the problem.

**Comment by nunomaduro** [comment] 2023-12-26 09:48
> it's an issue with Swoole and not Laravel Octane so feel free to close the issue.

**Closed by nunomaduro** 2023-12-26 09:48 UTC
Labels: needs more info

**Comment by L3o-pold** [comment] 2024-01-31 11:13
@sy-records no change with Swoole 5.1.2 😞

**Comment by L3o-pold** [comment] 2024-02-08 12:36
I do not reproduce on Swoole 5.1.2 but still with Octane so it seems to be an issue with how file are streamed on the Octane side.

Headers seems identical with or without Octane so my only guess is that the issue is located in the binary response content.

The Swoole code used to test it.

```php
$http = new Swoole\Http\Server(port: 9501);
$http->set([
    'log_file'                 => '/dev/null',
    'open_http2_protocol'      => true,
    'enable_static_handler'    => true,
    'document_root'            => '/var/www/static',
    'static_handler_locations' => ['/static', '/']
]);

$http->on('request', function (Swoole\Http\Request $request, Swoole\Http\Response $response) use ($http) {
    $response->end('ok');
});

$http->start();
```

**Comment by L3o-pold** [comment] 2024-02-08 12:50
@nunomaduro it seems to be related from this code https://github.com/laravel/octane/blob/2.x/src/Swoole/SwooleClient.php#L204 

Offset param is missing

**Comment by L3o-pold** [comment] 2024-02-14 11:30
Can we reopen this as setting the offset param seems to fix the issue?
