### ISSUE TITLE
Nova Timezone Doesn't work

### ISSUE THREAD

**Issue by zek** [laravel/octane#472] opened 2022-02-02 23:39 UTC
- Octane Version: 1.2.0
- Laravel Version: 8.81.0
- PHP Version: 8.1
- Server & Version: Swoole 
- Database Driver & Version: mysql 8

### Description:

`Nova::userTimezone` change does not reflect when using octane.

### Steps To Reproduce:

Install nova & octane, force timezone in NovaServiceProvider

```
    public function boot()
    {
        Nova::userTimezone(function ($request) {
            return 'UTC';
        });
    }
```

### Possible Solution

I've created a listener for `RequestReceived` event and changed timezone in the listener. That works but I don't get why it doesn't work when I change timezone in service provider.

**Comment by driesvints** [comment] 2022-02-03 09:43
It seems this is a duplicate of https://github.com/laravel/nova-issues/issues/3724

**Closed by driesvints** 2022-02-03 09:43 UTC
Labels: needs more info
