### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by sikhlana** [laravel/octane#285] opened 2021-05-19 09:43 UTC
- Octane Version: 1.0.1
- Laravel Version: 8.42.0
- PHP Version: 8.0.6
- Server & Version: Swoole 4.6.6
- Database Driver & Version: MySQL 5.6.10

### Description:
We are using AWS Aurora as our database and by default they have a `wait_timeout` and `interactive_timeout` of 300 seconds (5 minutes) so if the system does not receive any request for more than 5 minutes it starts throwing 

```
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away (SQL: ...)
```

The exception is being thrown while trying to authorize a user through the `auth` middleware.

### Steps To Reproduce:

1. Start an octane server.
2. Set the `wait_timeout` and `interactive_timeout` to a minimum for your MySQL server.
3. Make a few HTTP requests that uses MySQL connection. Enough requests to warm up all the workers.
4. Wait a couple of minutes more than the set timeouts.
5. Make another HTTP request.
6. An exception should be thrown.

### My input:

From what I've seen the framework will try to reconnect if a connection is dropped. Here's the exception trace:

```json
{
	"trace": [
		{
			"file": "/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
			"line": 752,
			"function": "runQueryCallback",
			"class": "Illuminate\\Database\\Connection",
			"type": "->"
		},
		{
			"file": "/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
			"line": 732,
			"function": "tryAgainIfCausedByLostConnection",
			"class": "Illuminate\\Database\\Connection",
			"type": "->"
		},
		{
			"file": "/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
			"line": 641,
			"function": "handleQueryException",
			"class": "Illuminate\\Database\\Connection",
			"type": "->"
		},
		{
			"file": "/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
			"line": 346,
			"function": "run",
			"class": "Illuminate\\Database\\Connection",
			"type": "->"
		},
		{
			"file": "/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
			"line": 2315,
			"function": "select",
			"class": "Illuminate\\Database\\Connection",
			"type": "->"
		},
		...
		{
			"file": "/app/vendor/laravel/framework/src/Illuminate/Auth/TokenGuard.php",
			"line": 85,
			"function": "retrieveByCredentials",
			"class": "App\\Auth\\RepositoryUserProvider",
			"type": "->"
		},
		{
			"file": "/app/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php",
			"line": 204,
			"function": "user",
			"class": "Illuminate\\Auth\\TokenGuard",
			"type": "->"
		},
		...
		{
			"file": "/app/vendor/laravel/octane/src/Worker.php",
			"line": 92,
			"function": "handle",
			"class": "Laravel\\Octane\\ApplicationGateway",
			"type": "->"
		},
		{
			"file": "/app/vendor/laravel/octane/bin/swoole-server",
			"line": 118,
			"function": "handle",
			"class": "Laravel\\Octane\\Worker",
			"type": "->"
		},
		{
			"function": "{closure}"
		},
		{
			"file": "/app/vendor/laravel/octane/bin/swoole-server",
			"line": 164,
			"function": "start",
			"class": "Swoole\\Server",
			"type": "->"
		}
	]
}
```

And it looks like the `tryAgainIfCausedByLostConnection()` is being called but that is not working.

After skimming through the code for Laravel's queue worker I see that if an exception is thrown due to lost connection, the worker process is exited and new worker is created (https://github.com/laravel/framework/blob/39459134a81ef3cc4b078b2f9de1495459bba50a/src/Illuminate/Queue/Worker.php#L377). Maybe implement something like that for the HTTP workers as well?

**Comment by sikhlana** [comment] 2021-05-19 14:01
Update: This also happens with **RoadRunner**.

**Comment by themsaid** [comment] 2021-05-24 15:05
The framework tries to reconnect only once. After that it'll throw the exception. Contact AWS support.

**Comment by sikhlana** [comment] 2021-05-24 18:45
@themsaid our production instances are disgustingly over provisioned to prevent any issue related to resources and connections and it never fails on `php-fpm` or on our other "long-running" services that gracefully handle connection pooling (NodeJS and Java).

I am currently trying to pinpoint exactly what is causing this issue since this might happen to others as well (even if the chances are slim as default MySQL's timeout is set to 8 hours).

**Comment by sikhlana** [comment] 2021-05-24 18:48
Another thing that I didn't mention here is that the authentication is using the default auth provider/guard instead of the one explicitly specified in the route middleware. I derived from the query that caused the exception since the auth guard is for administrators whereas the query being executed is for users and both have different tables. More on that later. Just sharing the situation as this might be related.

**Comment by sikhlana** [comment] 2021-05-24 20:09
@themsaid so I was able to pinpoint the issue: **separate read-write connection endpoints**

This is how the configuration is created for the connection to RDS:

```php
    [
        'master' => [
            'driver' => 'mysql',
            'read' => [
                'host' => [
                    env('MASTER_DB_READ_HOST', '127.0.0.1'),
                ],
            ],
            'write' => [
                'host' => [
                    env('MASTER_DB_WRITE_HOST', '127.0.0.1'),
                ],
            ],
            'port' => env('MASTER_DB_PORT', '3306'),
            'database' => env('MASTER_DB_DATABASE', 'forge'),
            'username' => env('MASTER_DB_USERNAME', 'forge'),
            'password' => env('MASTER_DB_PASSWORD', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
    ]
```

So if I remove the `read` and `write` keys everything works as expected. For some reason, having separate read and write connections messes up with the re-connection mechanism.

## How I did the test

1. Started the octane process
2. Created a HTTP endpoint that makes an arbitrary SQL to the `master::write` database
3. From the MySQL console, I killed the MySQL connection process that was created for step 2
4. Request the same HTTP endpoint
5. The exception is thrown

**Comment by themsaid** [comment] 2021-05-25 10:11
The issue is in Laravel core. I've opened a PR to fix it. Thanks for reporting https://github.com/laravel/framework/pull/37471

**Comment by hfpf** [comment] 2021-06-09 09:46
Does laravel:7.x have this problem as well? When it can be fixed in laravel:7.x?

**Comment by driesvints** [comment] 2021-06-09 09:49
@hfpf Laravel 7 isn't supported

**Closed** 2021-06-09 09:49 UTC
Labels: needs more info

**Comment by precamp-io** [comment] 2022-10-12 12:48
I am using Laravel 8 and have been working on this application for months and it suddenly appeared today.

**Comment by sikhlana** [comment] 2022-10-12 12:59
@precamp-io this error now occurs for packages/code outside of Laravel's scope. I have added a retry block where this issue persisted when using `doctrine/dbal`. Hope this example helps:

```php
        $tables = retry(2, function () {
            return DB::connection()
                ->getDoctrineSchemaManager()
                ->listTableNames();
        }, 10, function (Exception $e) {
            if (
                $e instanceof ConnectionLost ||
                Str::contains($e->getMessage(), 'out of order')
            ) {
                DB::connection()->reconnect();

                return true;
            }

            return false;
        });
```

**Comment by kevincobain2000** [comment] 2023-03-07 00:50
This happens in Laravel 10.x as well

**Comment by jeffreyvanhees** [comment] 2023-04-06 08:57
Today I got also this message suddenly (Vapor, Octane and Laravel 10). After a while it goes away and comes back. I've set the octane-database-session-parameters but it doesn't make sense:

```
octane-database-session-persist: true
octane-database-session-ttl: 10
```

**Comment by promatik** [comment] 2023-05-30 13:17
Happened to me after months of running an octane app without any issue.
I'm using a Digital Ocean droplet with a PostgreSQL database, at some point it must have gone down (probably an update) and since that all the requests were triggering **500**;

```log
SQLSTATE[HY000]: General error: 7 no connection to the server (Connection: pgsql, SQL: select id, name ...
```

A restart of the octane daemon quickly fixed the issue, but I'm afraid this happens again and I get a huge downtime of my app until I'm able to restart the daemon.

Any suggestions on how to make sure this doesn't happen again?

**Comment by smortexa** [comment] 2023-06-08 06:26
Increasing MySQL `max_connections` config helped in my case.

**Comment by daison12006013** [comment] 2023-07-12 05:40
Weird why this issue is closed, Laravel 10 is also affected with this, using OpenSwoole.

**Comment by hlspablo** [comment] 2024-09-04 19:13
> Today I got this message suddenly (Vapor, Octane and Laravel 10, all latest versions). After a while it goes away and comes back. I've set the octane-database-session-parameters but it doesn't make sense:
> 
> vapor.yaml
> 
> ```yaml
> octane-database-session-persist: true
> octane-database-session-ttl: 10
> ```
> 
> Any suggestions how to fix this?

anyone find a solution for this? still happens in Laravel 11x with vapor with the options above

**Comment by holdon1996** [comment] 2025-10-07 07:59
I'm currently experiencing this issue. Is there any way to resolve it?
I still want to use persistent to address the performance increase problem.
Currently, I've used the following code snippet in the RequestReceived event, but it's not effective.

```
try {
    DB::connection()->getPdo()->query('SELECT 1');
} catch (\Exception $e) {
    // Log to monitor
    Log::warning('Database connection lost, reconnecting', [
        'error' => $e->getMessage(),
        'code' => $e->getCode(),
        'url' => $event->request->url(),
    ]);

    // Reconnect
    DB::purge();
    DB::reconnect();
}
```

**Comment by johnflash4real** [comment] 2025-11-23 09:51
I started experiencing this on 2 of my apps as well, one laravel 11, another is 12. latest versions of octane. Never happened before enabling octane, and these apps are hosted on vapor.

Has anyone found a reliable workaround?
