### ISSUE TITLE
UrlGenerator warming up issue

### ISSUE THREAD

**Issue by gazzoy** [laravel/octane#809] opened 2024-01-13 09:27 UTC
### Octane Version

2.2.7

### Laravel Version

10.40.0

### PHP Version

8.2.14

### What server type are you using?

Swoole

### Server Version

5.1.1

### Description

Same as #784, #748.

When using `Route::bind()` and `URL::defaults()` with Octane, it seems that `UrlGenerator` keeps the same instance of `RouteUrlGenerator`, and so the defaults are cached between requests.

Especially, I believe the issue happens when we use `App\Http\Middleware\Authenticate` to handle login sessions.

### Steps To Reproduce

I created a public repo [gazzoy/laravel-octane-urlgenerator-issue](https://github.com/gazzoy/laravel-octane-urlgenerator-issue) with a fresh Laravel v10.40.0, Octane v2.2.7(swoole), Sail v1.27.0(php8.2), and the smallest code to reproduce the issue.

1. clone [gazzoy/laravel-octane-urlgenerator-issue](https://github.com/gazzoy/laravel-octane-urlgenerator-issue)
2. put an attached [.env.txt](https://github.com/laravel/octane/files/13927525/default.env.txt) on your local path as `gazzoy/laravel-octane-urlgenerator-issue/.env`.
3. run below commands.
```shell
$ cd gazzoy/laravel-octane-urlgenerator-issue
$ docker run --rm \
    -u "$(id -u):$(id -g)" \
    -v "$(pwd):/var/www/html" \
    -w /var/www/html \
    laravelsail/php82-composer:latest \
    composer install --ignore-platform-reqs
$ ./vendor/bin/sail build --no-cache
$ ./vendor/bin/sail up -d
$ ./vendor/bin/sail artisan migrate:refresh --seed
```
4. open your browser with:
`http://localhost/sample/paul/login`
It should show a page with a text "login page for paul" which is expected. 

5. open below url on the same browser:
`http://localhost/sample/john/home`
It redirects to `http://localhost/sample/paul/login` which doesn't make sense to me. Because, as of I understood, if `Route::bind()` and `URL::defaults()` work fine, we should be redirected to `http://localhost/sample/john/login`. Thefore, I believe it seems URL::defaults() keeps it states?

Having said that, I'm not too sure its actually Octane issue, so please let me know if this is not the case.

Just to clarify, my public repo has [3 commits](https://github.com/gazzoy/laravel-octane-urlgenerator-issue/commits/main/) as follows, but the first and second commits were just installing Laravel and Octane so you should be able to ignore it. The third commit is actually my original code to reproduce the issue.

1) [Fresh Laravel installation by Sail](https://github.com/gazzoy/laravel-octane-urlgenerator-issue/commit/49b11054443d4053439b15eae360c6a74ca30b3b)
2) [Installed Octane](https://github.com/gazzoy/laravel-octane-urlgenerator-issue/commit/19c5dbc4bb2904c1d2c9790dff831f41847feecd)
3) [Added code to reproduce the issue](https://github.com/gazzoy/laravel-octane-urlgenerator-issue/commit/85ed7a3be1e3077a20e5038aa1ab379854895980)

Please let me know if you have any questions.

**Comment by gazzoy** [comment] 2024-01-19 02:57
@nunomaduro Just a kindly reminder - this is the issue we discussed on https://github.com/laravel/octane/issues/784#issuecomment-1887380796

**Comment by Velizz** [comment] 2024-04-16 17:19
I've been able to replicate this issue, and its definitely a bug in source

**Comment by gazzoy** [comment] 2024-04-17 02:45
@Velizz Thank you for confirming its a bug!

**Comment by driesvints** [comment] 2024-04-17 06:46
Would greatly appreciate any help figuring this one out.

**Comment by gazzoy** [comment] 2024-04-18 02:28
@driesvints @nunomaduro 

I'm not sure it could be useful, but I added a failing test https://github.com/laravel/octane/pull/869 for this. As described in PR, it has another problem `Route [login] not defined` which slightly doesn't make sense to me. Couldn't figure out how to fix, so at this point I just leave it there.

**Comment by driesvints** [comment] 2024-04-18 09:04
Thanks @gazzoy

**Comment by Shkeats** [comment] 2024-05-07 10:04
@gazzoy in your demo app you aren't returning the user inside your Route::bind() closure. I think this could be the cause of your issue? Let me know.

![image](https://github.com/laravel/octane/assets/2048674/bc63fcd7-5ed0-4eba-8e1c-0e7a5958890a)

![image](https://github.com/laravel/octane/assets/2048674/05bfcc0e-3068-4de2-87db-907787b450e4)

**Comment by AlliBalliBaba** [comment] 2024-05-18 08:54
This issue might also be caused by a stale container reference like #887. I'll try to verify on my experimental branch when I have time.

**Comment by AlliBalliBaba** [comment] 2024-05-18 20:30
I was wrong, the `RouteUrlGenerator` actually just keeps its defaults across requests. If that's not intended, then Octane should probably do something like this in an event listener after each request:

`
$event->sandbox->make('url')->routeGenerator->defaultParameters = [];
`

Doing so requires additional changes in `laravel/framework` since the state of the routeGenerator is currently not accessible.

On a sidenote: Visiting the `home` url in the example of @gazzoy should always throw an error, since the `auth` middleware fires before the binding of the route is resolved. You would instead pass the username to the redirect in the `Authenticate` middleware.

**Comment by AlliBalliBaba** [comment] 2024-05-20 12:29
More specifically, it would be necessary to bind the state of the `RouteUrlGenerator` to the `$app` instance, since when setting a new `$request` in the `UrlGenerator`, we would want to keep defaults that were set during the booting of the app, but would want to discard defaults that were set during a request.

It would probably be hard to get such a PR merged since the changes are necessary in `laravel/framework`, but the tests need to be written in `laravel/octane`. Not sure how to best move forward here.

**Comment by dbpolito** [comment] 2024-05-20 22:02
I opened https://github.com/laravel/octane/pull/896 which should fix this issue... hopefully this gets merged soon, while it's not merged you guys can bring this to your codebase by creating this file:

```php
class CreateUrlSandbox
{
    public function handle($event): void
    {
        $event->sandbox->instance('url', clone $event->sandbox['url']);
    }
}
```

and add to your octane config:

```php
        RequestReceived::class => [
            ...Octane::prepareApplicationForNextOperation(),
            ...Octane::prepareApplicationForNextRequest(),
            CreateUrlSandbox::class,
        ],
```

**Comment by gazzoy** [comment] 2024-05-21 01:41
I can confirm #896 fix this issue.

In addition to put `CreateUrlSandbox` as @dbpolito suggested, I tweak `App\Http\Middleware\Authenticate` as following(mayby @AlliBalliBaba pointed?), then the redirect works as expected.

`App\Http\Middleware\Authenticate.php`
```diff
    protected function redirectTo(Request $request): ?string
    {
-        return $request->expectsJson() ? null : route('sample.login');
+        $user = $request->route()->parameters()['user'];
+        return $request->expectsJson() ? null : route('sample.login', ['user' => $user]);
    }
```

**Closed as completed** 2024-05-23 18:58 UTC
Labels: help wanted
